name: movie_app
description: Movies Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  arb_utils: ^0.1.0+1
  auto_route: ^7.4.0
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.6.5
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.2
  flutter_spinkit: ^5.2.0
  freezed: any
  freezed_annotation: any
  gap: ^3.0.0
  google_fonts: ^5.0.0
  http: ^1.0.0
  intl: ^0.18.0
  intl_utils: ^2.8.3
  json_annotation: any
  json_serializable: ^6.1.3
  mobx: any
  provider: ^6.0.5
  shared_preferences: ^2.1.2

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  #generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/

#flutter_intl:
#  enabled: true
